/**
 * Lirune Reader Mobile — release signing config plugin
 *
 * `android/` is regenerated by `expo prebuild`, so a hand-edited
 * `app/build.gradle` signing block only survives until the next prebuild — and a
 * release built without it silently gets signed with the debug key, which means it
 * cannot upgrade an installed copy.
 *
 * Credentials come from `~/.gradle/gradle.properties` (never committed, never in
 * app.json):
 *
 *   LIRUNE_RELEASE_STORE_FILE=/absolute/path/to/lirune-release.jks
 *   LIRUNE_RELEASE_STORE_PASSWORD=…
 *   LIRUNE_RELEASE_KEY_ALIAS=…
 *   LIRUNE_RELEASE_KEY_PASSWORD=…
 *
 * The `LIRUNE_UPLOAD_*` names from the release checklist are accepted as well, so
 * a machine that has been following that document keeps working. When they are
 * absent the plugin leaves the template untouched and Gradle falls back to its own
 * default, so a machine without the keystore still builds.
 */

const fs = require('fs');
const path = require('path');

const { AndroidConfig, withAppBuildGradle } = require('@expo/config-plugins');

const SIGNING_MARKER = 'LIRUNE_RELEASE_SIGNING';

/** Accepted property prefixes, in order of preference. */
const CREDENTIAL_PREFIXES = ['LIRUNE_RELEASE', 'LIRUNE_UPLOAD'];

/** Groovy that reads the first credential set that is actually present. */
function credentialExpressions(field) {
  return CREDENTIAL_PREFIXES.map((prefix) => `project.property('${prefix}_${field}')`).join('\n                ?: ');
}

function releaseSigningBlock() {
  return `        release {
            // ${SIGNING_MARKER}
            // Credentials come from ~/.gradle/gradle.properties; never commit them.
            if (project.hasProperty('${CREDENTIAL_PREFIXES[0]}_STORE_FILE') || project.hasProperty('${CREDENTIAL_PREFIXES[1]}_STORE_FILE')) {
                storeFile file(${credentialExpressions('STORE_FILE')})
                storePassword ${credentialExpressions('STORE_PASSWORD')}
                keyAlias ${credentialExpressions('KEY_ALIAS')}
                keyPassword ${credentialExpressions('KEY_PASSWORD')}
            }
        }`;
}

/**
 * Puts a `release` signing config into a generated `app/build.gradle`, and makes
 * `buildTypes.release` actually use it.
 *
 * The template ships `signingConfig signingConfigs.debug` for release, so a build
 * without this patch produces a "release" APK signed with the debug key — which
 * cannot upgrade the installed app and is not a distributable.
 */
function addReleaseSigning(buildGradle) {
  let patched = buildGradle;

  if (!patched.includes(SIGNING_MARKER)) {
    const block = releaseSigningBlock();
    // The whole signingConfigs block, its body, and its closing brace.
    const configs = /(signingConfigs\s*\{)([\s\S]*?)(\n    \})/.exec(patched);

    if (configs) {
      const releaseEntry = /\n        release\s*\{[\s\S]*?\n        \}/.exec(configs[2]);
      patched = patched.replace(
        configs[0],
        releaseEntry
          ? `${configs[1]}${configs[2].replace(releaseEntry[0], `\n${block}`)}${configs[3]}`
          : `${configs[1]}\n${configs[2].replace(/\s*$/, '')}\n${block}${configs[3]}`
      );
    } else {
      // No signingConfigs block at all: add one before android { }.
      patched = patched.replace(
        /\nandroid\s*\{/,
        `\n    signingConfigs {\n${block}\n    }\n\nandroid {`
      );
    }
  }

  // buildTypes.release must not keep the template's debug signing config.
  patched = patched.replace(
    /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]{0,400}?)signingConfig signingConfigs\.debug/,
    '$1signingConfig signingConfigs.release'
  );

  return patched;
}

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error('withReleaseSigning only supports the Groovy build.gradle template.');
    }
    const patched = addReleaseSigning(cfg.modResults.contents);
    if (patched !== cfg.modResults.contents) cfg.modResults.contents = patched;
    return cfg;
  });
};

module.exports.addReleaseSigning = addReleaseSigning;
module.exports.SIGNING_MARKER = SIGNING_MARKER;

/**
 * A keystore on the build machine is what makes a release installable as an
 * upgrade of the previous one; this is only used by the release checklist.
 */
function releaseCredentialsPresent() {
  const properties = path.join(
    process.env.USERPROFILE || process.env.HOME || '',
    '.gradle',
    'gradle.properties'
  );
  if (!fs.existsSync(properties)) return false;
  const contents = fs.readFileSync(properties, 'utf8');
  return CREDENTIAL_PREFIXES.some((prefix) =>
    new RegExp(`^\\s*${prefix}_STORE_FILE\\s*=`, 'm').test(contents)
  );
}

module.exports.releaseCredentialsPresent = releaseCredentialsPresent;
