/**
 * Lirune Reader Mobile — LiruneScreen config plugin
 *
 * `mobile/android/` is generated by `expo prebuild` and is git-ignored, so the
 * `LiruneScreen` Kotlin sources live in `plugins/native/lirune-screen/` and are
 * copied into the generated project on every Android prebuild, with
 * `LiruneScreenPackage` registered in `MainApplication.kt`.
 *
 * The Kotlin behind it is a window flag for "Keep Screen Awake". Both halves of
 * this plugin are idempotent: re-running prebuild over an already patched tree
 * changes nothing, so it is safe to run next to `withLiruneStorage`.
 */

const fs = require('fs');
const path = require('path');

const { withDangerousMod, withMainApplication } = require('@expo/config-plugins');

const PACKAGE_CLASS = 'LiruneScreenPackage';
const PACKAGE_IMPORT = `com.lirune.reader.screen.${PACKAGE_CLASS}`;
const KOTLIN_SOURCE_DIR = path.join(__dirname, 'native', 'lirune-screen');

/** Absolute path of the generated Android package source directory. */
function androidKotlinDir(platformProjectRoot) {
  return path.join(
    platformProjectRoot,
    'app',
    'src',
    'main',
    'java',
    'com',
    'lirune',
    'reader',
    'screen'
  );
}

function copyKotlinSources(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const { platformProjectRoot } = cfg.modRequest;
      if (!platformProjectRoot || !fs.existsSync(platformProjectRoot)) return cfg;

      const targetDir = androidKotlinDir(platformProjectRoot);
      fs.mkdirSync(targetDir, { recursive: true });

      for (const entry of fs.readdirSync(KOTLIN_SOURCE_DIR)) {
        if (!entry.endsWith('.kt')) continue;
        fs.copyFileSync(path.join(KOTLIN_SOURCE_DIR, entry), path.join(targetDir, entry));
      }
      return cfg;
    },
  ]);
}

/**
 * Registers `LiruneScreenPackage` in a generated `MainApplication.kt`.
 *
 * Exported so the transformation can be asserted on directly — the real check for
 * this plugin is that it produces valid Kotlin for every template shape React
 * Native 0.7x-0.8x has shipped.
 */
function registerPackageInMainApplication(contents) {
  // Already patched (prebuild ran twice, or another plugin registered it).
  if (new RegExp(`add\\(\\s*${PACKAGE_CLASS}\\s*\\(\\s*\\)`).test(contents)) {
    return contents;
  }

  if (!contents.includes(`import ${PACKAGE_IMPORT}`)) {
    const importLine = `import ${PACKAGE_IMPORT}`;
    const firstImport = /(^|\n)(import\s+[^\n]+\n)/.exec(contents);
    contents = firstImport
      ? contents.replace(firstImport[0], `${firstImport[0]}${importLine}\n`)
      : `${importLine}\n${contents}`;
  }

  // React Native 0.7x-0.8x generate `PackageList(this).packages.apply { … }`;
  // a plain `PackageList(this).packages` is rewritten into that shape instead.
  if (/PackageList\(this\)\.packages\.apply\s*\{/.test(contents)) {
    return contents.replace(
      /PackageList\(this\)\.packages\.apply\s*\{\s*\n/,
      `PackageList(this).packages.apply {\n          add(${PACKAGE_CLASS}())\n`
    );
  }
  if (/PackageList\(this\)\.packages\b/.test(contents)) {
    return contents.replace(
      /PackageList\(this\)\.packages\b/,
      `PackageList(this).packages.apply {\n          add(${PACKAGE_CLASS}())\n        }`
    );
  }
  throw new Error(
    'withLiruneScreen: no PackageList(this).packages block found in MainApplication.kt; ' +
      'the generated template changed and this plugin needs updating.'
  );
}

function withPackageRegistration(config) {
  return withMainApplication(config, (cfg) => {
    cfg.modResults.contents = registerPackageInMainApplication(cfg.modResults.contents);
    return cfg;
  });
}

module.exports = function withLiruneScreen(config) {
  return withPackageRegistration(copyKotlinSources(config));
};

module.exports.registerPackageInMainApplication = registerPackageInMainApplication;
module.exports.PACKAGE_CLASS = PACKAGE_CLASS;
module.exports.PACKAGE_IMPORT = PACKAGE_IMPORT;