/**
 * Lirune Reader Mobile — LiruneStorage config plugin
 *
 * `mobile/android/` is generated by `expo prebuild` and is git-ignored, so any
 * Kotlin source that only exists in the generated tree is destroyed by
 * `prebuild --clean`. This plugin makes the native `LiruneStorage` module part of
 * the repository:
 *
 *   1. the Kotlin sources are kept in `plugins/native/lirune-storage/` and copied
 *      into `android/app/src/main/java/com/lirune/reader/storage/` on every
 *      Android prebuild;
 *   2. `MainApplication.kt` — which prebuild regenerates — is patched to import
 *      and register `LiruneStoragePackage`.
 *
 * Both mods are idempotent: re-running prebuild over an already patched tree
 * changes nothing.
 */

const fs = require('fs');
const path = require('path');

const { withDangerousMod, withMainApplication } = require('@expo/config-plugins');

const PACKAGE_CLASS = 'LiruneStoragePackage';
const PACKAGE_IMPORT = `com.lirune.reader.storage.${PACKAGE_CLASS}`;
const KOTLIN_SOURCE_DIR = path.join(__dirname, 'native', 'lirune-storage');

/** Absolute path of the generated Android package source directory. */
function androidKotlinDir(platformProjectRoot) {
  return path.join(platformProjectRoot, 'app', 'src', 'main', 'java', 'com', 'lirune', 'reader', 'storage');
}

function copyKotlinSources(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const { platformProjectRoot } = cfg.modRequest;
      if (!platformProjectRoot || !fs.existsSync(platformProjectRoot)) return cfg;

      const targetDir = androidKotlinDir(platformProjectRoot);
      fs.mkdirSync(targetDir, { recursive: true });

      for (const entry of fs.readdirSync(KOTLIN_SOURCE_DIR)) {
        if (!entry.endsWith('.kt')) continue;
        fs.copyFileSync(path.join(KOTLIN_SOURCE_DIR, entry), path.join(targetDir, entry));
      }
      return cfg;
    },
  ]);
}

/**
 * Registers `LiruneStoragePackage` in a generated `MainApplication.kt`.
 *
 * Exported so the transformation can be asserted on directly — the real check for
 * this plugin is that it produces valid Kotlin for every template shape React
 * Native 0.7x-0.8x has shipped.
 */
function registerPackageInMainApplication(contents) {
  // Already patched (prebuild ran twice, or a previous plugin registered it).
  if (new RegExp(`add\\(\\s*${PACKAGE_CLASS}\\s*\\(\\s*\\)`).test(contents)) {
    return contents;
  }

  if (!contents.includes(`import ${PACKAGE_IMPORT}`)) {
    const importLine = `import ${PACKAGE_IMPORT}`;
    const firstImport = /(^|\n)(import\s+[^\n]+\n)/.exec(contents);
    contents = firstImport
      ? contents.replace(firstImport[0], `${firstImport[0]}${importLine}\n`)
      : `${importLine}\n${contents}`;
  }

  // React Native 0.7x-0.8x generate `PackageList(this).packages.apply { … }`;
  // a plain `PackageList(this).packages` is rewritten into that shape instead.
  if (/PackageList\(this\)\.packages\.apply\s*\{/.test(contents)) {
    return contents.replace(
      /PackageList\(this\)\.packages\.apply\s*\{\s*\n/,
      `PackageList(this).packages.apply {\n          add(${PACKAGE_CLASS}())\n`
    );
  }
  if (/PackageList\(this\)\.packages\b/.test(contents)) {
    return contents.replace(
      /PackageList\(this\)\.packages\b/,
      `PackageList(this).packages.apply {\n          add(${PACKAGE_CLASS}())\n        }`
    );
  }
  throw new Error(
    `withLiruneStorage: no PackageList(this).packages block found in MainApplication.kt; ` +
      'the generated template changed and this plugin needs updating.'
  );
}

function withPackageRegistration(config) {
  return withMainApplication(config, (cfg) => {
    cfg.modResults.contents = registerPackageInMainApplication(cfg.modResults.contents);
    return cfg;
  });
}

module.exports = function withLiruneStorage(config) {
  return withPackageRegistration(copyKotlinSources(config));
};

module.exports.registerPackageInMainApplication = registerPackageInMainApplication;