// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  ...expoConfig,
  {
    ignores: [
      "dist/*",
      "node_modules/*",
      ".expo/*",
      // Generated by scripts/gen-pdfjs.js — a vendored pdf.js payload.
      "services/pdf/pdfjsAssets.ts",
    ],
    rules: {
      "react-hooks/set-state-in-effect": "off",
      "react-hooks/immutability": "off",
    }
  },
  {
    // Build-time Node scripts and Expo config plugins, not application code.
    files: ["scripts/**/*.js", "plugins/**/*.js"],
    languageOptions: {
      globals: {
        __dirname: "readonly",
        require: "readonly",
        module: "writable",
        process: "readonly",
        console: "readonly",
      },
    },
  }
]);
