#!/usr/bin/env python3
"""
Lirune Reader - Real-File QA corpus generator.

Creates a legally-clean corpus of synthetic book files for manual/automated QA
of the Android app (Lirune Reader, Expo/RN). Every byte in the corpus is
generated by this script from original placeholder prose written for QA
purposes - no third-party or proprietary books are copied.

Usage (from repo root or the corpus dir):

    python Lirune-Android-RealFile-QA/generate_corpus.py

Requirements: Python 3.9+ and Pillow (PIL). Nothing else; the PDF writer,
MOBI/RAR stubs and ZIP assembly are implemented here so the corpus has no
external archiver or proprietary library dependency.
"""

import base64
import binascii
import io
import os
import struct
import textwrap
import zlib
import zipfile

from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
VALID_DIR = os.path.join(HERE, "valid")
EDGE_DIR = os.path.join(HERE, "edge")

# Fixed timestamp keeps regeneration byte-stable for reproducible QA runs.
FIXED_TS = (2026, 1, 15, 9, 30, 0)
ZIP_DATE = (2026, 1, 15, 9, 30, 0)


# ---------------------------------------------------------------------------
# Original QA placeholder prose (written for this corpus; no copyrighted text)
# ---------------------------------------------------------------------------

BOOK_TITLE = "The Lighthouse at Sker Point"
BOOK_AUTHOR = "A. Wren (QA Corpus)"
BOOK_SUBJECT = "Reader test document"

CH_TITLES = [
    "1. The Keeper's Ledger",
    "2. Fog on the Sound",
    "3. What the Lamp Recorded",
    "4. The Long Dark Interval",
    "5. A Light Kept Anyway",
]

CH_PARAS = [
    [
        "Maren wrote the log in a hand so small it looked like a line of ants. "
        "The wind had been steady for nine days, and the entries repeated "
        "themselves: clear at four, clear at eight, nothing on the horizon.",
        "She had inherited the ledger with the post. Nobody had explained the "
        "job, only the objects - a brass key, a tin of wick, a book with a "
        "leather spine and no title. The keeper's rule was simple and "
        "unwritten: the light does not go out.",
        "On the eleventh day the wind changed direction, and with it came a "
        "sound she had never heard before, low and patient, like something "
        "large moving slowly under the water of the sound.",
    ],
    [
        "Fog arrived without ceremony. It simply was there at noon, a soft "
        "grey wall that swallowed the harbour and then the last hundred metres "
        "of rock below the tower.",
        "In fog the work became ritual. Wick trimmed, lens polished, clock "
        "wound, log signed. Maren found she liked the ritual. It gave the "
        "hours an order the fog had taken away.",
        "She talked to the sea a little. It was not madness, exactly; it was "
        "the ordinary courtesy of living alone with something that listens. "
        "The sea never answered, but it never left either.",
    ],
    [
        "The lens was a machine of brass and glass that turned on a clockwork "
        "drum. Maren cleaned it the way she imagined her grandmother had, with "
        "a soft cloth and a great deal of patience.",
        "Behind the glass the flame flattened and widened. She wrote down the "
        "time, the weather, the number of ships that answered. The numbers "
        "mattered. Somebody, somewhere, was reading them.",
        "That night a ship answered. Three short flashes, meaning all well. "
        "Maren wrote it down, and then sat for a while in the dark, letting "
        "the beam go over her face again and again.",
    ],
    [
        "The dark interval began on a Thursday and lasted four days. The "
        "generator failed, the spare coil was corroded, and the road was under "
        "water.",
        "She trimmed wick by hand every four hours through the long nights, "
        "moving the lamp with a rope and a shoulder, holding the light on the "
        "channel the way she had been taught - a foot left of the marker, no "
        "more, no less.",
        "The ships kept coming in. She counted nine of them, and she never once "
        "wrote the word failure in the ledger, because it had not happened. "
        "The light was still there. That was the whole of the job.",
    ],
    [
        "The relief boat came in spring. Maren handed over the key, the tin, "
        "and the book with the leather spine, and said nothing about the "
        "eleven days of wind or the ship that answered.",
        "The new keeper read the ledger for a long time. At the entry for the "
        "thirty-first night he stopped and looked up, and Maren told him what "
        "she had done with the rope, and the foot left of the marker.",
        "Then she walked up the path to the bus, carrying nothing much, in a "
        "coat that smelled of oil and salt. Behind her the lamp turned, and "
        "kept turning, and the light did not go out.",
    ],
]

EMOJI_LINES = [
    "Beacon log: lamp nominal \U0001F30D calm sea \U0001F30A",
    "Observer note: gulls heading inland \U0001F426 \U0001F427",
    "Weather: overcast \U0001F327 with brief \U0001F326 showers",
    "Mood marker: steady resolve \U0001F937, small victories \U0001F31F",
    "Mixed-script proof: ASCII / 日本語 / 中文 / 한국어 / Русский / \U0001F40D",
]


def qa_prose(seed: int = 0):
    """Return a deterministic prose block used by TXT/PDF/FB2/EPUB variants."""
    paras = []
    for ti, title in enumerate(CH_TITLES):
        paras.append(title)
        for p in CH_PARAS[(ti + seed) % len(CH_PARAS)]:
            paras.append(" ".join(textwrap.wrap(p, 78)))
    return paras


# ---------------------------------------------------------------------------
# Image helpers
# ---------------------------------------------------------------------------

def make_cover_jpeg(width=600, height=900, title=BOOK_TITLE) -> bytes:
    """Simple synthetic cover art (gradient + lighthouse silhouette)."""
    img = Image.new("RGB", (width, height), (18, 26, 40))
    d = ImageDraw.Draw(img)
    for y in range(height):
        t = y / max(1, height - 1)
        d.line(
            [(0, y), (width, y)],
            fill=(int(18 + 60 * t), int(26 + 70 * t), int(40 + 95 * t)),
        )
    # sea band
    d.rectangle([0, int(height * 0.72), width, height], fill=(12, 30, 46))
    for i in range(6):
        y = int(height * 0.74) + i * 14
        d.line([(0, y), (width, y)], fill=(26 + i * 6, 58 + i * 8, 78 + i * 6))
    # beam
    d.polygon(
        [(width * 0.62, height * 0.30), (width, height * 0.20),
         (width, height * 0.40), (width * 0.62, height * 0.34)],
        fill=(250, 226, 150),
    )
    # tower
    tx, tw = int(width * 0.58), int(width * 0.10)
    d.polygon(
        [(tx - tw // 2, int(height * 0.66)), (tx + tw // 2, int(height * 0.66)),
         (tx + tw // 3, int(height * 0.34)), (tx - tw // 3, int(height * 0.34))],
        fill=(226, 226, 220),
    )
    d.rectangle([tx - tw // 2 - 6, int(height * 0.30), tx + tw // 2 + 6, int(height * 0.345)],
                fill=(198, 92, 70))
    d.rectangle([tx - 6, int(height * 0.62), tx + 6, int(height * 0.70)], fill=(150, 60, 48))
    for i, line in enumerate(textwrap.wrap(title, 22)[:3]):
        d.text((28, height - 120 + i * 20), line, fill=(236, 236, 230))
    d.text((28, height - 60), BOOK_AUTHOR, fill=(180, 190, 205))
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=78, optimize=True)
    return buf.getvalue()


def make_comic_page(index: int, total: int, width=900, height=1350) -> bytes:
    """Synthetic comic page: panels, captions, balloons (no real artwork)."""
    img = Image.new("RGB", (width, height), (247, 245, 238))
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, width, 70], fill=(28, 32, 40))
    d.text((24, 26), "LIRUNE QA COMIC - PAGE %d OF %d" % (index, total),
           fill=(240, 240, 235))
    margin, gap = 40, 24
    panel_w = width - margin * 2
    panel_h = (height - 120 - margin - gap * 3) // 4
    palette = [
        ((222, 232, 240), (40, 60, 90)),
        ((238, 232, 214), (110, 80, 40)),
        ((226, 238, 226), (50, 90, 60)),
        ((238, 226, 232), (100, 50, 80)),
    ]
    for p in range(4):
        top = 90 + p * (panel_h + gap)
        bg, fg = palette[(index + p) % len(palette)]
        d.rectangle([margin, top, width - margin, top + panel_h], fill=bg, outline=fg, width=4)
        # simple panel content: horizon + shapes
        hz = top + int(panel_h * 0.62)
        d.line([(margin + 6, hz), (width - margin - 6, hz)], fill=fg, width=3)
        for k in range(3):
            cx = margin + 80 + k * 220 + (index * 17) % 60
            r = 30 + (index * 7 + k * 11) % 40
            d.ellipse([cx - r, hz - r - 10, cx + r, hz + r - 10], outline=fg, width=3)
        d.rectangle([margin + 6, top + 6, margin + 6 + 250, top + 6 + 24], fill=fg)
        d.text((margin + 12, top + 10), "PANEL %d.%d" % (index, p + 1), fill=(250, 250, 246))
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=72, optimize=True)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# EPUB 3
# ---------------------------------------------------------------------------

def xhtml_doc(title: str, body: str, css_href: str = "style.css") -> bytes:
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!DOCTYPE html>\n'
        '<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops"'
        ' xml:lang="en" lang="en">\n'
        '  <head>\n'
        '    <meta charset="utf-8" />\n'
        '    <title>%s</title>\n'
        '    <link rel="stylesheet" type="text/css" href="%s" />\n'
        '  </head>\n'
        '  <body>\n%s\n  </body>\n</html>\n' % (title, css_href, body)
    ).encode("utf-8")


def build_epub(path: str) -> None:
    cover = make_cover_jpeg()
    css = (
        "body{font-family:serif;line-height:1.5;margin:5%;}\n"
        "h1,h2{font-family:sans-serif;}\n"
        "p{text-align:justify;margin:0.8em 0;}\n"
    ).encode("utf-8")

    chapters = []
    for i, ctitle in enumerate(CH_TITLES, start=1):
        paras = "\n".join(
            "    <p>%s</p>" % " ".join(textwrap.wrap(p, 200))
            for p in CH_PARAS[(i - 1) % len(CH_PARAS)]
        )
        body = (
            "    <section epub:type=\"chapter\" id=\"ch%d\">\n"
            "      <h1>%s</h1>\n%s\n"
            "      <p class=\"note\">QA placeholder chapter %d of %d.</p>\n"
            "    </section>" % (i, ctitle, paras, i, len(CH_TITLES))
        )
        chapters.append(("chapter%02d.xhtml" % i, xhtml_doc(ctitle, body)))

    cover_body = (
        '    <section epub:type="cover" id="cover">\n'
        '      <img src="images/cover.jpg" alt="Cover art" />\n'
        "    </section>"
    )
    nav_items = "".join(
        '        <li><a href="chapter%02d.xhtml">%s</a></li>\n' % (i, t)
        for i, t in enumerate(CH_TITLES, start=1)
    )
    nav = xhtml_doc(
        "Contents",
        '    <nav epub:type="toc" id="toc">\n'
        '      <h1>Contents</h1>\n'
        "      <ol>\n%s      </ol>\n"
        "    </nav>" % nav_items,
    )
    nav_items_ncx = "".join(
        '    <navPoint id="np%d" playOrder="%d">\n'
        "      <navLabel><text>%s</text></navLabel>\n"
        "      <content src=\"chapter%02d.xhtml\"/>\n"
        "    </navPoint>\n" % (i, i, t, i)
        for i, t in enumerate(CH_TITLES, start=1)
    )
    ncx = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">\n'
        "  <head>\n"
        '    <meta name="dtb:uid" content="urn:uuid:lirune-qa-epub-0001" />\n'
        "    <meta name=\"dtb:depth\" content=\"1\" />\n"
        "    <meta name=\"dtb:totalPageCount\" content=\"0\" />\n"
        "    <meta name=\"dtb:maxPageNumber\" content=\"0\" />\n"
        "  </head>\n"
        '  <docTitle><text>%s</text></docTitle>\n'
        '  <navMap>\n%s  </navMap>\n'
        "</ncx>\n" % (BOOK_TITLE, nav_items_ncx)
    ).encode("utf-8")

    manifest_images = (
        '    <item id="cover-img" href="images/cover.jpg" media-type="image/jpeg"'
        ' properties="cover-image" />\n'
    )
    manifest_chapters = "".join(
        '    <item id="ch%d" href="chapter%02d.xhtml" media-type="application/xhtml+xml" />\n'
        % (i, i)
        for i in range(1, len(CH_TITLES) + 1)
    )
    opf = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="pub-id"'
        ' xml:lang="en">\n'
        '  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">\n'
        '    <dc:identifier id="pub-id">urn:uuid:lirune-qa-epub-0001</dc:identifier>\n'
        '    <dc:title>%s</dc:title>\n'
        '    <dc:creator>%s</dc:creator>\n'
        '    <dc:language>en</dc:language>\n'
        '    <dc:subject>%s</dc:subject>\n'
        '    <dc:description>Synthetic EPUB 3 QA fixture: 5 sections, EPUB 3 nav document,'
        ' legacy NCX fallback, and a cover image.</dc:description>\n'
        '    <dc:publisher>Lirune Reader QA Corpus</dc:publisher>\n'
        '    <dc:rights>Public domain - original placeholder text written for Lirune QA.</dc:rights>\n'
        '    <dc:date>2026-01-15</dc:date>\n'
        '    <meta property="dcterms:modified">2026-01-15T09:30:00Z</meta>\n'
        '    <meta name="cover" content="cover-img" />\n'
        "  </metadata>\n"
        "  <manifest>\n"
        '    <item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav" />\n'
        '    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml" />\n'
        '    <item id="cover-page" href="cover.xhtml" media-type="application/xhtml+xml" />\n'
        "%s%s"
        '    <item id="css" href="style.css" media-type="text/css" />\n'
        "  </manifest>\n"
        "  <spine toc=\"ncx\">\n"
        '    <itemref idref="cover-page" linear="no" />\n'
        "%s"
        "  </spine>\n"
        "</package>\n"
        % (
            BOOK_TITLE,
            BOOK_AUTHOR,
            BOOK_SUBJECT,
            manifest_chapters,
            manifest_images,
            "".join('    <itemref idref="ch%d" />\n' % i for i in range(1, len(CH_TITLES) + 1)),
        )
    ).encode("utf-8")

    container = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">\n'
        "  <rootfiles>\n"
        '    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml" />\n'
        "  </rootfiles>\n"
        "</container>\n"
    ).encode("utf-8")

    with zipfile.ZipFile(path, "w") as z:
        # mimetype MUST be the first entry and STORED (uncompressed).
        zi = zipfile.ZipInfo("mimetype", date_time=ZIP_DATE)
        zi.compress_type = zipfile.ZIP_STORED
        z.writestr(zi, "application/epub+zip")
        def add(name: str, data: bytes) -> None:
            info = zipfile.ZipInfo(name, date_time=ZIP_DATE)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            z.writestr(info, data)

        add("META-INF/container.xml", container)
        add("OEBPS/content.opf", opf)
        add("OEBPS/nav.xhtml", nav)
        add("OEBPS/toc.ncx", ncx)
        add("OEBPS/style.css", css)
        add("OEBPS/cover.xhtml", xhtml_doc("Cover", cover_body))
        add("OEBPS/images/cover.jpg", cover)
        for name, data in chapters:
            add("OEBPS/" + name, data)


# ---------------------------------------------------------------------------
# PDF (hand-rolled writer: text pages + XMP metadata, optional JPEG cover)
# ---------------------------------------------------------------------------

def esc_pdf(text: str) -> bytes:
    out = text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")
    return out.encode("latin-1", "replace")


class Pdf:
    """Minimal PDF 1.7 writer: Helvetica text pages, Info dict, XMP metadata."""

    def __init__(self):
        self.objects = [None]  # 1-based

    def add(self, payload: bytes) -> int:
        self.objects.append(payload)
        return len(self.objects) - 1

    def reserve(self) -> int:
        self.objects.append(b"")
        return len(self.objects) - 1

    def set(self, num: int, payload: bytes) -> None:
        self.objects[num] = payload

    def stream(self, dict_body: bytes, data: bytes) -> int:
        head = b"<< " + dict_body + b" /Length " + str(len(data)).encode() + b" >>\nstream\n"
        return self.add(head + data + b"\nendstream")

    def build(self, root: int, info: int, xmp: int | None = None) -> bytes:
        out = bytearray(b"%PDF-1.7\n%\xe2\xe3\xcf\xd3\n")
        offsets = [0] * len(self.objects)
        for num in range(1, len(self.objects)):
            offsets[num] = len(out)
            out += str(num).encode() + b" 0 obj\n" + self.objects[num] + b"\nendobj\n"
        xref_pos = len(out)
        n = len(self.objects)
        out += b"xref\n0 " + str(n).encode() + b"\n"
        out += b"0000000000 65535 f \n"
        for num in range(1, n):
            out += ("%010d 00000 n \n" % offsets[num]).encode()
        out += (
            b"trailer\n<< /Size " + str(n).encode() + b" /Root " + str(root).encode()
            + b" 0 R /Info " + str(info).encode() + b" 0 R"
            + (b" /Metadata " + str(xmp).encode() + b" 0 R" if xmp else b"")
            + b" >>\nstartxref\n" + str(xref_pos).encode() + b"\n%%EOF\n"
        )
        return bytes(out)

    def text_page_obj(self, lines, font_num, font_size=11, leading=15, margin=60,
                      media=(0, 0, 612, 792)):
        """Create a page object whose content stream holds the given lines."""
        content = [b"BT", b"/F1 %d Tf" % font_size, b"%d TL" % leading,
                   b"1 0 0 1 %d %d Tm" % (margin, media[3] - 50)]
        cur_size = font_size
        for size, text in lines:
            if text == "":
                content.append(b"T*")
                continue
            if size != cur_size:
                content.append(b"/F1 %d Tf" % size)
                cur_size = size
            content.append(b"(" + esc_pdf(text) + b") Tj")
            content.append(b"T*")
        content.append(b"ET")
        stream = self.stream(b"", b"\n".join(content))
        res = (b"/Resources << /Font << /F1 " + str(font_num).encode()
               + b" 0 R >> /ProcSet [/PDF /Text] >>")
        page = self.reserve()
        self.set(
            page,
            b"<< /Type /Page /Parent 0 0 R /MediaBox ["
            + b" ".join(str(v).encode() for v in media)
            + b"] "
            + res
            + b" /Contents " + str(stream).encode() + b" 0 R >>",
        )
        return page

    def font(self):
        return self.add(
            b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>"
        )


def wrap_ascii(text: str, width: int = 92):
    return textwrap.wrap(text, width)


def build_pdf_text(path: str) -> None:
    pdf = Pdf()
    font = pdf.font()
    flat = qa_prose()
    chunk1 = flat[:8]
    chunk2 = flat[8:] or ["End of QA sample document."]

    def body_lines(chunks, start_with_heading=None):
        lines = []
        if start_with_heading:
            lines.append(start_with_heading)
            lines.append(("", ""))
        for para in chunks:
            if len(para) < 60 and para[:2].strip().rstrip(".").isdigit():
                lines.append((13, para))
                lines.append(("", ""))
            else:
                lines.extend((11, wl) for wl in wrap_ascii(para))
                lines.append(("", ""))
        return lines

    lines1 = (
        [(20, BOOK_TITLE), (12, "by " + BOOK_AUTHOR),
         (10, BOOK_SUBJECT + " - QA fixture"), ("", "")]
        + body_lines(chunk1)
    )
    lines2 = body_lines(chunk2)
    lines2.append((10, "End of document. Synthetic content for Lirune Reader QA only."))

    p1 = pdf.text_page_obj(lines1, font)
    p2 = pdf.text_page_obj(lines2, font)
    pages_obj = pdf.add(
        b"<< /Type /Pages /Kids [" + str(p1).encode() + b" 0 R " + str(p2).encode()
        + b" 0 R] /Count 2 >>"
    )
    for p in (p1, p2):
        pdf.set(p, pdf.objects[p].replace(b"/Parent 0 0 R", b"/Parent " + str(pages_obj).encode() + b" 0 R"))
    root = pdf.add(
        b"<< /Type /Catalog /Pages " + str(pages_obj).encode() + b" 0 R >>"
    )
    info = pdf.add(
        b"<< /Title (" + esc_pdf(BOOK_TITLE) + b") /Author (" + esc_pdf(BOOK_AUTHOR)
        + b") /Subject (" + esc_pdf(BOOK_SUBJECT) + b") /Creator (Lirune QA corpus generator)"
        b" /Producer (Lirune QA corpus generator) /Keywords (QA; pdf; sample)"
        b" /CreationDate (D:20260115093000Z) /ModDate (D:20260115093000Z) >>"
    )
    xmp = pdf.stream(
        b"/Type /Metadata /Subtype /XML", xmp_packet(BOOK_TITLE, BOOK_AUTHOR, BOOK_SUBJECT)
    )
    # attach the metadata stream to the catalog
    pdf.set(root, b"<< /Type /Catalog /Pages " + str(pages_obj).encode()
            + b" 0 R /Metadata " + str(xmp).encode() + b" 0 R >>")
    with open(path, "wb") as f:
        f.write(pdf.build(root, info, xmp))


def xmp_packet(title: str, author: str, subject: str, thumbnail: str | None = None) -> bytes:
    thumb_block = ""
    if thumbnail:
        thumb_block = (
            '   <xmpMM:Thumbnails>\n'
            '    <rdf:Bag>\n'
            '     <rdf:li rdf:parseType="Resource">\n'
            '      <xmpMM:Thumbnail rdf:resource="%s" width="600" height="900"'
            ' alt="Cover"/>\n'
            "     </rdf:li>\n"
            "    </rdf:Bag>\n"
            "   </xmpMM:Thumbnails>\n"
            "   <xmpMM:DocumentID>urn:uuid:lirune-qa-pdf-0002</xmpMM:DocumentID>\n"
            "   <xmpMM:InstanceID>urn:uuid:lirune-qa-pdf-0002-i</xmpMM:InstanceID>\n" % thumbnail
        )
    return (
        '<?xpacket begin="\ufeff" id="W5M0MpCehiHzreSzNTczkc9d"?>\n'
        '<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Lirune QA corpus generator">\n'
        ' <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">\n'
        '  <rdf:Description rdf:about=""\n'
        '    xmlns:dc="http://purl.org/dc/elements/1.1/">\n'
        "   <dc:format>application/pdf</dc:format>\n"
        "   <dc:title><rdf:Alt><rdf:li xml:lang=\"x-default\">%s</rdf:li></rdf:Alt></dc:title>\n"
        "   <dc:creator><rdf:Seq><rdf:li>%s</rdf:li></rdf:Seq></dc:creator>\n"
        "   <dc:description><rdf:Alt><rdf:li xml:lang=\"x-default\">%s"
        " Synthetic PDF QA fixture.</rdf:li></rdf:Alt></dc:description>\n"
        "   <dc:subject><rdf:Bag><rdf:li>%s</rdf:li></rdf:Bag></dc:subject>\n"
        "   <dc:publisher>Lirune Reader QA Corpus</dc:publisher>\n"
        "   <dc:rights>Public domain - original placeholder text written for Lirune QA."
        "</dc:rights>\n"
        "   <xmp:CreateDate xmlns:xmp=\"http://ns.adobe.com/xap/1.0/\""
        " xmp:date=\"2026-01-15T09:30:00Z\"/>\n"
        "%s"
        "  </rdf:Description>\n"
        " </rdf:RDF>\n"
        "</x:xmpmeta>\n"
        '<?xpacket end="w"?>\n'
        % (title, author, subject, subject, thumb_block)
    ).encode("utf-8")


def build_pdf_cover(path: str) -> None:
    jpeg = make_cover_jpeg()
    img = Image.open(io.BytesIO(jpeg))
    w, h = img.size

    pdf = Pdf()
    font = pdf.font()
    img_obj = pdf.add(
        b"<< /Type /XObject /Subtype /Image /Name /Thumb /Width " + str(w).encode()
        + b" /Height " + str(h).encode()
        + b" /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length "
        + str(len(jpeg)).encode() + b" >>\nstream\n" + jpeg + b"\nendstream"
    )
    # page 1: full-page cover image drawn from the embedded JPEG
    content1 = (
        b"q\n595 0 0 842 0 0 cm\n/Im1 Do\nQ\n"
        b"BT\n/F1 9 Tf\n1 1 1 rg\n10 12 Td\n("
        + esc_pdf("Embedded DCTDecode cover. XMP xmpMM thumbnail references /Thumb.")
        + b") Tj\nET\n"
    )
    s1 = pdf.stream(b"", content1)
    p1 = pdf.reserve()
    lines = [(16, BOOK_TITLE), (10, "by " + BOOK_AUTHOR), ("", "")]
    for para in qa_prose()[:9]:
        if len(para) < 60:
            lines.append((12, para))
            lines.append(("", ""))
        else:
            lines.extend((11, wl) for wl in wrap_ascii(para))
            lines.append(("", ""))
    p2 = pdf.text_page_obj(lines, font, media=(0, 0, 595, 842))
    pages_obj = pdf.add(
        b"<< /Type /Pages /Kids [" + str(p1).encode() + b" 0 R " + str(p2).encode()
        + b" 0 R] /Count 2 >>"
    )
    pdf.set(
        p1,
        b"<< /Type /Page /Parent " + str(pages_obj).encode()
        + b" 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im1 "
        + str(img_obj).encode() + b" 0 R >> /Font << /F1 " + str(font).encode()
        + b" 0 R >> /ProcSet [/PDF /Text] >> /Contents " + str(s1).encode() + b" 0 R >>",
    )
    pdf.set(p2, pdf.objects[p2].replace(b"/Parent 0 0 R", b"/Parent " + str(pages_obj).encode() + b" 0 R"))
    root = pdf.add(b"<< /Type /Catalog /Pages " + str(pages_obj).encode() + b" 0 R >>")
    info = pdf.add(
        b"<< /Title (" + esc_pdf(BOOK_TITLE + " (Cover Edition)") + b") /Author ("
        + esc_pdf(BOOK_AUTHOR) + b") /Subject (PDF cover-image QA fixture) /Keywords (QA; pdf; cover; xmp)"
        b" /Creator (Lirune QA corpus generator) /Producer (Lirune QA corpus generator)"
        b" /CreationDate (D:20260115093000Z) >>"
    )
    xmp = pdf.stream(
        b"/Type /Metadata /Subtype /XML",
        xmp_packet(BOOK_TITLE + " (Cover Edition)", BOOK_AUTHOR, "PDF cover-image QA fixture",
                   thumbnail="cover.jpg"),
    )
    pdf.set(
        root,
        b"<< /Type /Catalog /Pages " + str(pages_obj).encode() + b" 0 R /Metadata "
        + str(xmp).encode() + b" 0 R >>",
    )
    with open(path, "wb") as f:
        f.write(pdf.build(root, info, xmp))


# ---------------------------------------------------------------------------
# TXT variants
# ---------------------------------------------------------------------------

def build_large_txt(path: str, target_bytes: int = 1_250_000) -> int:
    """Mixed-encoding UTF-8 text > 1 MB, built to stress chunkIndex.ts."""
    ascii_sentences = [
        "The keeper wrote the hour, the wind, and the number of ships that answered.",
        "Fog held the sound for four days and the light was not permitted to fail.",
        "Wick trimmed, lens polished, clock wound, log signed, lamp turned.",
        "A hull passed at two in the morning and signalled three short flashes.",
        "The road was under water, so the relief boat was three weeks late.",
        "Every entry in the ledger repeated itself until the pattern became a kind of calm.",
    ]
    cjk_lines = [
        "灯台の記録: 午前四時、水平線上に船影なし。",
        "灯塔守の手記 第二章 - 霧の中から見た光。",
        "第三章: ランプは消えない。",
        "第四章: 長い暗闇の期間、そして手拭いの重用。",
        "第五章: それでも灯りはここにある。",
    ]
    hangul = "第五条: 등대 기록 보관함의 온도 측정값."
    mixed_header = (
        "The Lighthouse at Sker Point\n"
        "by A. Wren (QA Corpus) - large TXT chunking fixture\n"
        + "=" * 78 + "\n"
        "This file is intentionally larger than 1 MB and mixes ASCII, CJK, and\n"
        "astral-plane emoji so that chunkIndex.ts chunk cutting, byte-offset\n"
        "mapping, and UTF-8 window reads are all exercised.\n"
        + "=" * 78 + "\n\n"
    )

    parts = [mixed_header]
    size = len(mixed_header.encode("utf-8"))
    chapter_no = 0
    while size < target_bytes:
        chapter_no += 1
        block = []
        block.append("CHAPTER %d\n" % chapter_no)
        block.append("-" * 78 + "\n")
        # plain paragraph lines
        for s in ascii_sentences:
            block.append(" ".join(textwrap.wrap(s, 78)) + "\n")
        # CJK / multilingual lines
        block.append(cjk_lines[chapter_no % len(cjk_lines)] + "\n")
        block.append(hangul + "\n")
        # emoji lines (4-byte UTF-8, surrogate pairs in JS)
        block.append(EMOJI_LINES[chapter_no % len(EMOJI_LINES)] + "\n")
        # indented lines to exercise space lookahead
        block.append("    indented note:  indented text with runs of spaces    inside\n")
        # long unbroken line (~6 KB) to exercise newline lookahead fallback
        block.append("LONG_LINE " + ("abcdefghij0123456789" * 340) + " END_LONG_LINE\n")
        # emoji-heavy long line
        block.append("EMOJI_RUN " + ("\U0001F525\U0001F30D\U0001F6F8 " * 60) + "\n")
        # CRLF line endings in this block only
        block.append("CRLF_BLOCK: this paragraph uses carriage-return line endings.\r\n")
        block.append("So does this one, and it contains CJK: 光の記録。\r\n")
        # line without trailing newline followed by next chapter (join hazard)
        if chapter_no % 5 == 0:
            block.append("NO_TRAILING_NEWLINE_MARKER_%d" % chapter_no)
        else:
            block.append(".\n")
        block.append("\n")
        text = "".join(block)
        parts.append(text)
        size += len(text.encode("utf-8"))
    data = "".join(parts).encode("utf-8")
    with open(path, "wb") as f:
        f.write(data)
    return len(data)


def build_encoded_txt() -> None:
    latin1_text = (
        "Caf\xe9 na\xefve \xfcber stra\xdfe \x96 good faith\r\n"
        "Pi\xe8ce jointe, cr\xe8me br\xfbl\xe9e, d\xe9j\xe0 vu.\r\n"
        "Espa\xf1ol: ma\xf1ana se\xf1or, a\xf1o nuevo, cora\xf1\xf3n.\r\n"
        "Italiano: perch\xe9, pi\xf9, citt\xf9, cos\xec.\r\n"
        "Portugu\xeas: cora\xe7\xe3o, heartbeat, \xe7, \xe3.\r\n"
    )
    with open(os.path.join(EDGE_DIR, "latin1-encoded.txt"), "wb") as f:
        f.write(latin1_text.encode("latin-1", "replace"))

    utf16_text = (
        "UTF-16 LE sample for non-UTF8 decoding fallback\r\n"
        "The quick brown fox jumps over the lazy dog.\r\n"
        "Unicode: 日本語のテキスト、中文文本、한국어 텍스트.\r\n"
        "Astral plane: \U0001F4DA \U0001F5FC\feff(end of line)\r\n"
    )
    with open(os.path.join(EDGE_DIR, "utf16le-encoded.txt"), "wb") as f:
        f.write(b"\xff\xfe" + utf16_text.encode("utf-16-le"))


# ---------------------------------------------------------------------------
# FB2
# ---------------------------------------------------------------------------

def build_fb2(path: str) -> None:
    cover = make_cover_jpeg(width=300, height=450)
    b64 = base64.b64encode(cover).decode("ascii")
    lines = [b64[i:i + 76] for i in range(0, len(b64), 76)]

    sections = []
    for i, ctitle in enumerate(CH_TITLES, start=1):
        body = []
        for p in CH_PARAS[(i - 1) % len(CH_PARAS)]:
            for chunk in textwrap.wrap(p, 72):
                body.append("      <p>%s</p>" % chunk)
        if i == 2:
            body.append("      <empty-line/>")
            body.append("      <poem><stanza><v>Wick trimmed, lens polished,</v>"
                        "<v>clock wound, log signed, lamp turned.</v></stanza></poem>")
        body.append("      <subtitle>Section %d of %d</subtitle>" % (i, len(CH_TITLES)))
        sections.append(
            "    <section>\n"
            "      <title><p>%s</p></title>\n"
            "%s\n"
            "    </section>" % (ctitle, "\n".join(body))
        )

    xml = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<FictionBook xmlns="http://www.gribuser.ru/xml/fictionbook/2.0"'
        ' xmlns:l="http://www.w3.org/1999/xlink">\n'
        '  <description>\n'
        "    <title-info>\n"
        "      <genre>science_fiction</genre>\n"
        "      <author><first-name>A.</first-name><last-name>Wren</last-name></author>\n"
        "      <book-title>%s</book-title>\n"
        "      <annotation><p>Synthetic FictionBook 2 QA fixture: coverpage image,"
        " author, two genres, annotation, and %d chapters.</p></annotation>\n"
        "      <keywords>qa, fb2, fictionbook, lighthouses</keywords>\n"
        "      <date>2026-01-15</date>\n"
        "      <coverpage><image l:href=\"#cover.jpg\"/></coverpage>\n"
        "      <lang>en</lang>\n"
        "      <src-lang>en</src-lang>\n"
        "      <sequence name=\"Lirune QA Corpus\"/>\n"
        "    </title-info>\n"
        "    <document-info>\n"
        "      <author><nickname>Lirune QA Corpus</nickname></author>\n"
        "      <program-used>generate_corpus.py</program-used>\n"
        "      <date>2026-01-15</date>\n"
        "      <id>urn:uuid:lirune-qa-fb2-0001</id>\n"
        "      <version>1.0</version>\n"
        "    </document-info>\n"
        "  </description>\n"
        "  <body>\n"
        "    <title><p>%s</p></title>\n"
        "%s\n"
        "  </body>\n"
        "  <binary id=\"cover.jpg\" content-type=\"image/jpeg\">%s\n"
        "%s\n"
        "  </binary>\n"
        "</FictionBook>\n"
        % (
            BOOK_TITLE,
            len(CH_TITLES),
            BOOK_TITLE,
            "\n".join(sections),
            "\n".join(lines[: len(lines) // 2]),
            "\n".join(lines[len(lines) // 2:]),
        )
    )
    with open(path, "wb") as f:
        f.write(xml.encode("utf-8"))


# ---------------------------------------------------------------------------
# CBZ
# ---------------------------------------------------------------------------

def build_cbz(path: str, pages: int = 8) -> None:
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        for i in range(1, pages + 1):
            data = make_comic_page(i, pages)
            info = zipfile.ZipInfo("pages/page%02d.jpg" % i, date_time=ZIP_DATE)
            info.compress_type = zipfile.ZIP_DEFLATED
            z.writestr(info, data)
        # ComicInfo.xml + a small hidden-style macOS metadata entry, both ignored
        # by ZipInspectionService / CBZ reader - useful negative coverage.
        info = zipfile.ZipInfo("ComicInfo.xml", date_time=ZIP_DATE)
        z.writestr(
            info,
            (
                '<?xml version="1.0" encoding="utf-8"?>\n'
                '<ComicInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n'
                "  <Title>%s (QA Comic)</Title>\n"
                "  <Series>Lirune QA Corpus</Series>\n"
                "  <Number>1</Number>\n"
                "  <Summary>Synthetic comic archive used to test lazy page streaming.</Summary>\n"
                "  <Writer>Unknown</Writer>\n"
                "  <PageCount>%d</PageCount>\n"
                "</ComicInfo>\n" % (BOOK_TITLE, pages)
            ).encode("utf-8"),
        )


# ---------------------------------------------------------------------------
# HTML book
# ---------------------------------------------------------------------------

def build_html(path: str) -> None:
    thumb = make_cover_jpeg(width=240, height=360)
    b64 = base64.b64encode(thumb).decode("ascii")
    paras = []
    for ctitle in CH_TITLES[:3]:
        paras.append("  <h2>%s</h2>" % ctitle)
        for p in CH_PARAS[CH_TITLES.index(ctitle) % len(CH_PARAS)][:2]:
            paras.append("  <p>%s</p>" % p)
    html = (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "  <head>\n"
        '    <meta charset="utf-8">\n'
        '    <meta name="viewport" content="width=device-width, initial-scale=1">\n'
        '    <meta name="author" content="%s">\n'
        '    <meta name="description" content="Single-file HTML book fixture: title, meta'
        ' tags, headings, paragraphs, and one inline image.">\n'
        '    <meta name="generator" content="Lirune QA corpus generator">\n'
        '    <meta name="dcterms.created" content="2026-01-15">\n'
        "    <title>%s</title>\n"
        "    <style>\n"
        "      body { font-family: Georgia, serif; line-height: 1.6; margin: 1.25rem; }\n"
        "      h1 { font-size: 1.6rem; }\n"
        "      h2 { font-size: 1.2rem; margin-top: 2rem; }\n"
        "      figure { margin: 1rem 0; text-align: center; }\n"
        "    </style>\n"
        "  </head>\n"
        "  <body>\n"
        "    <article>\n"
        "      <h1>%s</h1>\n"
        "      <p><em>by %s</em></p>\n"
        "      <figure>\n"
        '        <img src="data:image/jpeg;base64,%s" alt="Inline cover art" width="160">\n'
        "        <figcaption>Inline (base64 data URI) image - exercises HTML cover extraction."
        "</figcaption>\n"
        "      </figure>\n"
        "%s\n"
        "      <hr>\n"
        "      <p class=\"colophon\">Synthetic single-file HTML QA fixture. All text is"
        " original placeholder prose written for Lirune Reader QA.</p>\n"
        "    </article>\n"
        "  </body>\n"
        "</html>\n" % (BOOK_AUTHOR, BOOK_TITLE, BOOK_TITLE, BOOK_AUTHOR, b64, "\n".join(paras))
    )
    with open(path, "wb") as f:
        f.write(html.encode("utf-8"))


# ---------------------------------------------------------------------------
# Edge-case binaries
# ---------------------------------------------------------------------------

def build_edge_cases(epub_bytes: bytes) -> None:
    # 1. zero-byte epub
    open(os.path.join(EDGE_DIR, "zero-byte.epub"), "wb").close()

    # 2. corrupt zip renamed to .epub: valid local-file-header signature,
    #    garbage payload, no central directory.
    with open(os.path.join(EDGE_DIR, "corrupt-zip.epub"), "wb") as f:
        f.write(b"PK\x03\x04")
        f.write(b"\x14\x00\x00\x00\x08\x00")
        f.write(os.urandom(0) + b"LIRUNE-QA-CORRUPT-ZIP-PAYLOAD-")
        f.write(binascii.hexlify(os.urandom(64)))
        f.write(b"\r\ntruncated central directory removed on purpose\r\n")

    # 3. non-UTF8 text files (written by build_encoded_txt)

    # 4. ZIP container holding one valid EPUB (nested path)
    with zipfile.ZipFile(os.path.join(EDGE_DIR, "epub-in-zip.zip"), "w", zipfile.ZIP_DEFLATED) as z:
        info = zipfile.ZipInfo("books/sample-minimal.epub", date_time=ZIP_DATE)
        z.writestr(info, epub_bytes)

    # 5. MOBI (unsupported) - minimal but structurally valid PDB/PalmDOC/MOBI
    with open(os.path.join(EDGE_DIR, "unsupported.mobi"), "wb") as f:
        f.write(build_mobi())

    # 6. CBR (unsupported RAR) - minimal RAR5 stream with signature + headers
    with open(os.path.join(EDGE_DIR, "unsupported.cbr"), "wb") as f:
        f.write(build_rar5())


def build_mobi() -> bytes:
    text = (
        "The Lighthouse at Sker Point\r\n"
        "by A. Wren (QA Corpus)\r\n\r\n"
        "Synthetic MOBI/PDB stub used only to verify that Lirune Reader rejects"
        " the .mobi extension with a clear unsupported-format message. The text"
        " body is original placeholder prose written for Lirune QA.\r\n"
    ).encode("utf-8")

    name = b"LiruneQAUnsupportedSample"
    pad = name + b"\x00" * (32 - len(name))
    rec_count = 3
    header_len = 78
    record_info_len = 8 * rec_count
    rec0_off = header_len + record_info_len
    rec0 = b"\x01\x00\x00\x00" + struct.pack(">IHHH", len(text), 1, 4096, 0)  # PalmDOC
    rec0 = rec0.ljust(16, b"\x00")[:16]
    rec1_off = rec0_off + len(rec0)
    mobi_header = bytearray(232)
    mobi_header[0:4] = b"MOBI"
    struct.pack_into(">H", mobi_header, 4, 232)      # header length
    mobi_header[6] = 2                              # mobi type: book
    struct.pack_into(">I", mobi_header, 8, 0x54524541)  # unique id
    struct.pack_into(">I", mobi_header, 12, 6)      # file version
    struct.pack_into(">I", mobi_header, 20, len(text))   # first non-book index
    struct.pack_into(">I", mobi_header, 24, 0)      # full name offset
    struct.pack_into(">I", mobi_header, 28, 0)      # full name length
    struct.pack_into(">I", mobi_header, 36, 0)      # locale
    struct.pack_into(">I", mobi_header, 44, 0)      # input language
    struct.pack_into(">I", mobi_header, 48, 0)      # output language
    struct.pack_into(">I", mobi_header, 64, len(text))  # extra data 0 size
    struct.pack_into(">I", mobi_header, 84, 232)    # first image index
    rec1 = bytes(mobi_header)
    rec2_off = rec1_off + len(rec1)
    rec2 = text

    rec_infos = b"".join(
        struct.pack(">I", 0 if i == 0 else i) + struct.pack(">I", off)
        for i, off in enumerate((rec0_off, rec1_off, rec2_off))
    )
    header = bytearray(b"\x00" * header_len)
    header[0:32] = pad
    struct.pack_into(">HH", header, 32, 0, 0)            # attributes, version
    struct.pack_into(">III", header, 36, 0, 0, 0)        # creation, modification, backup dates
    struct.pack_into(">I", header, 48, 0)                 # modify number
    struct.pack_into(">II", header, 52, 0, 0)            # appinfo offset, sortinfo offset
    header[60:64] = b"BOOK"
    header[64:68] = b"TYPE"
    struct.pack_into(">I", header, 68, 0x12345678)       # unique id seed
    struct.pack_into(">I", header, 72, 2)                # next record list id
    struct.pack_into(">H", header, 76, rec_count)
    return bytes(header) + rec_infos + rec0 + rec1 + rec2


def _vint(value: int) -> bytes:
    out = bytearray()
    while True:
        b = value & 0x7F
        value >>= 7
        if value:
            out.append(b | 0x80)
        else:
            out.append(b)
            return bytes(out)


def _rar_header(htype: int, body: bytes) -> bytes:
    size_field = _vint(len(body) + 1)  # header type vint + body
    raw = size_field + _vint(htype) + body
    return struct.pack("<I", zlib.crc32(raw) & 0xFFFFFFFF) + raw


def build_rar5() -> bytes:
    signature = b"Rar!\x1a\x07\x01\x00"
    # main archive header (type 1)
    main = _rar_header(
        1,
        _vint(0)                      # archive flags
        + _vint(0)                    # volume number
        + _vint(0)                    # extra area size
        + b"\x00" * 8,                # reserved
    )
    payload = make_cover_jpeg(width=160, height=240)
    name = "cover.jpg".encode("utf-8")
    file_body = (
        _vint(0x0004)                 # file flags: data CRC32 present
        + _vint(len(payload))         # unpacked size
        + _vint(0x20)                 # attributes
        + struct.pack("<I", zlib.crc32(payload) & 0xFFFFFFFF)  # data CRC32
        + _vint(0)                    # compression info: version 0, method 0 (store)
        + _vint(0)                    # host OS: Windows
        + _vint(len(name))
        + name
    )
    file_hdr = _rar_header(2, file_body)
    eof = _rar_header(5, _vint(1))    # end of archive header
    return signature + main + file_hdr + payload + eof


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    os.makedirs(VALID_DIR, exist_ok=True)
    os.makedirs(EDGE_DIR, exist_ok=True)

    epub_path = os.path.join(VALID_DIR, "sample-minimal.epub")
    build_epub(epub_path)
    with open(epub_path, "rb") as f:
        epub_bytes = f.read()

    build_pdf_text(os.path.join(VALID_DIR, "sample-text.pdf"))
    build_pdf_cover(os.path.join(VALID_DIR, "sample-cover-xmp.pdf"))
    size = build_large_txt(os.path.join(VALID_DIR, "sample-large-mixed.txt"))
    print("sample-large-mixed.txt: %d bytes" % size)
    build_fb2(os.path.join(VALID_DIR, "sample-story.fb2"))
    build_cbz(os.path.join(VALID_DIR, "sample-comic.cbz"))
    build_html(os.path.join(VALID_DIR, "sample-book.html"))

    build_encoded_txt()
    build_edge_cases(epub_bytes)

    print("corpus written to", HERE)
    for d in (VALID_DIR, EDGE_DIR):
        for name in sorted(os.listdir(d)):
            p = os.path.join(d, name)
            print("  %-9s %-28s %9d bytes" % (os.path.basename(d), name, os.path.getsize(p)))


if __name__ == "__main__":
    main()
